More checks about repositories

diff --git a/what-the-duck b/what-the-duck
--- a/what-the-duck
+++ b/what-the-duck
@@ -1,7 +1,10 @@
 #!/bin/bash
+RED='\033[0;31m'
+NC='\033[0m' # No Color
 
 if ! [ -x "$(command -v rospack)" ]; then
-  echo 'rospack is not accessible. You need to activate ros and compile the repo.' >&2
+  echo -e "${RED}rospack is not accessible${NC}." >&2
+  echo -e "You need to activate ROS and compile the repo." >&2
   exit 1
 fi
 
@@ -11,7 +14,7 @@ rospack find what_the_duck
 if [ $? -eq 0 ]; then
     echo
 else
-    echo "Package what_the_duck not compiled."
+    echo -e "Error: ${RED}Package what_the_duck not compiled.${NC}" >&2
 fi
 
 
