- updated scripts --> TO BE FINISHED

diff --git a/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_fleet_messaging b/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_fleet_messaging
--- a/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_fleet_messaging
+++ b/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_fleet_messaging
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Argument check
+# Argument check: show usage
 if [[ $# -eq 0 ]] ; then
     echo "Aborting...no interface argument given!"
     exit 1
@@ -8,31 +8,39 @@ fi
 
 # Check the interface
 WIFACE=$1
+for item in "$@" ; do
+    # Remove argument for $DUCKIETOWN_ROOT/environment.sh
+    shift;
+done
 iwconfig $WIFACE | grep -v "no wireless extensions."
-if [[ $WIFACE != "" && $? -ne 0 ]] ; then
+if [[ $? -ne 0 ]] ; then
     echo "Aborting...Interface" $WIFACE "is not a WiFi interface!"
     exit 2
 fi
 
 source $DUCKIETOWN_ROOT/environment.sh
-
-# Install ZeroMQ
-./install_zeromq
 if [[ $? -ne 0 ]] ; then
-    echo "Aborting...installing ZeroMQ failed!"
+    echo "Aborting...there is something wrong with the environment!"
     exit 3
 fi
 
+# Install ZeroMQ
+# ./install_zmq
+if [[ $? -ne 0 ]] ; then
+    echo "Aborting...installing ZeroMQ failed!"
+    exit 4
+fi
+
 # Install ProtoBuf
-./install_protobuf
+# ./install_protobuf
 if [[ $? -ne 0 ]] ; then
     echo "Aborting...installing ProtoBuf failed!"
-    exit 4
+    exit 5
 fi
 
 # Install the mesh network
 ./install_meshnet
 if [[ $? -ne 0 ]] ; then
     echo "Aborting...installing mesh network failed!"
-    exit 5
+    exit 6
 fi
