Slight modification of installation and creation of uninstallers - uninstall_meshnet and unconfigure_meshnet: needed to uninstall the mesh network from a duckiebot or a laptop - configure_meshnet: modified to use a custom netmask - get_ip and get_subnet: functions to read the ip address and netmask using slash notation (incl. checking, if network address is written correctly) - install_fleet_messaging, install_meshnet:  using the new network address with slash notation - install_protobuf and install_zmq: uninstalling pip packages with sudo (to be on the safe side)

diff --git a/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_fleet_messaging b/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_fleet_messaging
--- a/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_fleet_messaging
+++ b/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_fleet_messaging
@@ -4,16 +4,15 @@
 if [[ $# -ne 2 ]] ; then
     echo "Usage:"
     echo "Important: the script MUST be run from its location!"
-    echo "./install_fleet_messaging <wifi-iface> <static-ip>"
+    echo "./install_fleet_messaging <wifi-iface> <network>"
     echo "Write arguments without <>."
-    echo "<wifi-iface> is a WiFi interface that can be found with iwconfig."
-    echo "(interface used for the mesh network)"
-    echo "<static-ip> is a static IP address for the duckiebot."
-    echo "Every duckiebot needs a UNIQUE IP address!"
+    echo "<wifi-iface> is a WiFi interface that can be found with iwconfig (interface used for the mesh network)."
+    echo "<network> is the duckiebot mesh network address (static IP address and subnet in slash notation, e.g. 192.168.15.30/24 for a subnet of 255.255.255.0)."
+    echo "Every duckiebot needs a UNIQUE IP address and the subnet must be equal on all the duckiebots!"
     exit 1
 fi
 WIFACE=$1
-IPADDR=$2
+NETADDR=$2
 
 # Check the interface
 for item in "$@" ; do
@@ -26,21 +25,32 @@ if [[ $? -ne 0 ]] ; then
     exit 2
 fi
 
-source $DUCKIETOWN_ROOT/environment.sh
+# Check the IP Address
+CHECK_IP=$(./get_ip $NETADDR)
 if [[ $? -ne 0 ]] ; then
-    echo "Aborting...there is something wrong with the environment!"
+    echo "Aborting...the network address" $NETADDR "has a wrong format!"
     exit 3
 fi
 
-# Install ZeroMQ
-./install_zmq
+source $DUCKIETOWN_ROOT/environment.sh
 if [[ $? -ne 0 ]] ; then
-    echo "Aborting...installing ZeroMQ failed!"
+    echo "Aborting...there is something wrong with the environment!"
     exit 4
 fi
 
+# Install ZeroMQ
+#./install_zmq
+if [[ $? -ne 0 ]] ; then
+    echo "Aborting...installation of ZeroMQ failed!"
+    exit 5
+fi
+
 # Install ProtoBuf
-./install_protobuf
+#./install_protobuf
 
 # Install the mesh network
-./install_meshnet $WIFACE $IPADDR
+./install_meshnet $WIFACE $NETADDR
+if [[ $? -ne 0 ]] ; then
+    exit 6
+    echo "Aborting...the installation of the mesh network failed!"
+fi
diff --git a/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_meshnet b/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_meshnet
--- a/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_meshnet
+++ b/catkin_ws/src/30-localization-and-planning/fleet_messaging/dependencies/install_meshnet
@@ -1,19 +1,32 @@
 #!/bin/bash
 
+# Get the arguments
+WIFACE=$1
+NETADDR=$2
+
+# Get the IP Address and the subnet
+IPADDR=$(./get_ip $NETADDR)
+if [[ $? -ne 0 ]] ; then
+    echo "Aborting...the network address has the wrong format!"
+    exit 1
+fi
+SUBNET=$(./get_subnet $NETADDR)
+
 # Install B.A.T.M.A.N. advanced and dependencies
 sudo apt install -y bridge-utils wireless-tools batctl
 
 # Configure the mesh network
-sudo ./configure_meshnet $1 $2
+sudo ./configure_meshnet $WIFACE $IPADDR $SUBNET
 sudo chmod +x start_batman
+sudo chmod +x rem_bat_iface
 sudo chmod +x stop_batman
 sudo mv start_batman /etc/network/if-pre-up.d/
+sudo mv rem_bat_iface /etc/network/if-down.d/
 sudo mv stop_batman /etc/network/if-post-down.d/
 
 RED='\033[0;31m'
 NC='\033[0m'
 echo -e "${RED}"
 echo -e "Installation of the mesh network finished!"
-echo -e "Remove previous occurrences of $1 from /etc/network/interfaces"
-echo -e "Check /etc/network/interfaces for uninstalling the mesh network!"
+echo -e "Run ./uninstall_meshnet to uninstall the mesh network!"
 echo -e "${NC}"
